spring:
  application:
    name: gatewayserver
  config:
    import: configserver:http://localhost:8030/
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
#      redis-rate-limiter:
#        config:
#          default:
#
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

info:
  app:
    name: accounts
    description: "StealyBits gateway"
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    com:
      stealybits:
        gatewayserver: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
