services:
  common-network-service:
    networks:
      - banknetwork

  microservice-base-config:
    extends:
      service: common-network-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_completed_successfully
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8030
      SPRING_PROFILES_ACTIVE: default